palces = ["Beijing","Shanghai","Nanchang","Tianjin","Chengdu"]
print(palces)
print(sorted(palces))
print(palces)
print(sorted(palces,reverse=True))
print(palces)
palces.reverse()
print(palces)
palces.reverse()
print(palces)
palces.sort()
print(palces)
palces.sort(reverse=True)
print(palces)
